[general]
import = ["~/.config/alacritty/themes/themes/tomorrow_night_bright.toml"]
live_config_reload = true

[window]
opacity = 0.75
decorations = "None"
startup_mode = "Maximized"
padding = { x = 0, y = 0 }

[colors.primary]
background = "#061917" # Replace with your preferred hex code
foreground = "#c0caf5"

[font]
normal = { family = "Fira Code Nerd Font", style = "Medium" }
size = 11.0

[[hints.enabled]]
command = "xdg-open"                            # Use "open" on macOS
hyperlinks = true
post_processing = true
binding = { key = "O", mods = "Control|Shift" }

[scrolling]
history = 50000
multiplier = 3  # Number of lines scrolled per mouse wheel notch
