[general]
import = ["~/.config/alacritty/themes/themes/tomorrow_night_bright.toml"]

[window]
opacity = 0.8
decorations = "None"
startup_mode = "Maximized"

[font]
normal = { family = "Fira Code Nerd Font", style = "Medium" }
size = 11.0
